name: Lint and Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - epic/**
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup.yaml
      - name: Lint
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup.yaml
      - name: Unit tests
        run: yarn test
